### ISSUE TITLE
vlmcsd无法激活office2021，但是这个KMS（kms.cangshui.net）可以，请问怎么搭建？centos

### ISSUE THREAD

**Issue by Yamazaki-wu** [netnr/kms#1]
office tool plus用这个（kms.cangshui.net）地址可以激活。请问centos下怎么搭建啊？

**Comment by netnr** [comment]
看秋水的一键脚本

**Comment by Yamazaki-wu** [comment]
秋水的脚本也是搭建的vlmcsd？那其实就是vlmscd是可以激活office2021的，可我也是按照网上的教程一步一步成功搭建vlmscd啊。还是说vlmscd有新版本？

**Comment by netnr** [comment]
不清楚

**Comment by Yamazaki-wu** [comment]
那这个地址（kms.cangshui.net）是您搭建的么？

**Comment by netnr** [comment]
不是

**Comment by Yamazaki-wu** [comment]
0.0
那看来也没什么办法了。vlmscd也激活不了最新的。
